blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: ../../../../discussions
    about: Please ask and answer questions here.
  - name: Security
    url: ../../../../security
    about: Please report security vulnerabilities here.
