name: Build

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  cache: 'npm'
            - run: npm ci
            - run: npm run build
            - run: |
                  date > build
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "generated"
                  git push
            - name: Deploy to GitHub Pages
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  # deploy to gh-pages branch
                  target_branch: gh-pages
                  # deploy the default output dir of VuePress
                 build_dir: .
              env:
                  # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
                  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
